### ISSUE TITLE
Add a License 

### ISSUE THREAD

**Issue by apowellgt** [pengwyn/AutoParameters.jl#1]
Hey, me again. We have your SentryIntegration.jl running in development (thank you!) and I believe it relies on this package. Would you consider adding a license here as well?

**Comment by pengwyn** [comment]
Of course! It's exciting to see the packages get some use.

**Comment by pengwyn** [comment]
I should add here that this package has been superseded in part by core functionality, and also by some other packages out there. I haven't been keeping up to date, but there is likely something simpler to deal with in new projects.
